import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        {/* Parent flex container */}
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <Navbar />

          {/* Main content with gradient background */}
          <main className="flex-1 ml-72 p-6 bg-gradient-to-b from-[#1a1a3b] via-[#2a2a5b] to-gray-200">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
